In [1]:
import pandas as pd

# Correct file path
path = r'C:\Users\User\Documents\NewDataSet.csv'

# Load the data
df = pd.read_csv(path)

# Display the first few rows
df.head()

,Title,Release Date,Developer,Publisher,Genres,Product Rating,User Score,User Ratings Count,Platforms Info,Platforms Info Cleaned,Platform Metascores,Platform Metascore Counts
0,Ziggurat (2012),17/2/2012,Action Button Entertainment,Freshuu Inc.,Action,Not Rated,6.900000,14.0,"[{'Platform': 'iOS (iPhone/iPad)', 'Platform M...",iOS (iPhone/iPad),83,Based on 18 Critic Reviews
1,4X4 EVO 2,15/11/2001,Terminal Reality,Gathering,Auto Racing Sim,Rated E For Everyone,6.894852,NaN,"[{'Platform': 'Xbox', 'Platform Metascore': '5...","Xbox, PC, GameCube","59, 69, 56","Based on 15 Critic Reviews, Based on 9 Critic ..."
2,MotoGP 2 (2001),22/1/2002,Namco,Namco,Auto Racing Sim,Rated E For Everyone,5.800000,NaN,"[{'Platform': 'PlayStation 2', 'Platform Metas...",PlayStation 2,78,Based on 18 Critic Reviews
3,Gothic 3,14/11/2006,Piranha Bytes,Aspyr,Western RPG,Rated T For Teen,7.500000,832.0,"[{'Platform': 'PC', 'Platform Metascore': '63'...",PC,63,Based on 39 Critic Reviews
4,Siege Survival: Gloria Victis,18/5/2021,FishTankStudio,Black Eye Games,RPG,Not Rated,6.500000,10.0,"[{'Platform': 'PC', 'Platform Metascore': '69'...",PC,69,Based on 12 Critic Reviews

In [3]:
path = r'C:\Users\User\Downloads\User_Dataset.csv'

userset = pd.read_csv(path)

userset.head

<bound method NDFrame.head of         user_id                                              Title  user_score
0        user_9                                    Ziggurat (2012)        3.01
1       user_81                                    Ziggurat (2012)        7.79
2       user_66                                    Ziggurat (2012)        8.31
3       user_47                                    Ziggurat (2012)        8.40
4       user_49                                    Ziggurat (2012)        2.72
...         ...                                                ...         ...
211315  user_51  Lemony Snicket's A Series of Unfortunate Event...        3.11
211316  user_62  Lemony Snicket's A Series of Unfortunate Event...        4.84
211317  user_77  Lemony Snicket's A Series of Unfortunate Event...        2.53
211318  user_74  Lemony Snicket's A Series of Unfortunate Event...        9.68
211319  user_92  Lemony Snicket's A Series of Unfortunate Event...        9.68

[211320 rows x 3 columns]>

In [5]:
data = pd.merge(df,userset, on='Title')
data.head()

,Title,Release Date,Developer,Publisher,Genres,Product Rating,User Score,User Ratings Count,Platforms Info,Platforms Info Cleaned,Platform Metascores,Platform Metascore Counts,user_id,user_score
0,Ziggurat (2012),17/2/2012,Action Button Entertainment,Freshuu Inc.,Action,Not Rated,6.9,14.0,"[{'Platform': 'iOS (iPhone/iPad)', 'Platform M...",iOS (iPhone/iPad),83,Based on 18 Critic Reviews,user_9,3.01
1,Ziggurat (2012),17/2/2012,Action Button Entertainment,Freshuu Inc.,Action,Not Rated,6.9,14.0,"[{'Platform': 'iOS (iPhone/iPad)', 'Platform M...",iOS (iPhone/iPad),83,Based on 18 Critic Reviews,user_81,7.79
2,Ziggurat (2012),17/2/2012,Action Button Entertainment,Freshuu Inc.,Action,Not Rated,6.9,14.0,"[{'Platform': 'iOS (iPhone/iPad)', 'Platform M...",iOS (iPhone/iPad),83,Based on 18 Critic Reviews,user_66,8.31
3,Ziggurat (2012),17/2/2012,Action Button Entertainment,Freshuu Inc.,Action,Not Rated,6.9,14.0,"[{'Platform': 'iOS (iPhone/iPad)', 'Platform M...",iOS (iPhone/iPad),83,Based on 18 Critic Reviews,user_47,8.40
4,Ziggurat (2012),17/2/2012,Action Button Entertainment,Freshuu Inc.,Action,Not Rated,6.9,14.0,"[{'Platform': 'iOS (iPhone/iPad)', 'Platform M...",iOS (iPhone/iPad),83,Based on 18 Critic Reviews,user_49,2.72

In [7]:
data.isna().sum()

Title                         6594
Release Date                  7275
Developer                     8342
Publisher                     8342
Genres                        6594
Product Rating                   0
User Score                       0
User Ratings Count           47581
Platforms Info                   0
Platforms Info Cleaned        6718
Platform Metascores           6718
Platform Metascore Counts     6718
user_id                          0
user_score                       0
dtype: int64

In [9]:
data = data.dropna()

data.isna().sum()

Title                        0
Release Date                 0
Developer                    0
Publisher                    0
Genres                       0
Product Rating               0
User Score                   0
User Ratings Count           0
Platforms Info               0
Platforms Info Cleaned       0
Platform Metascores          0
Platform Metascore Counts    0
user_id                      0
user_score                   0
dtype: int64

In [11]:
data.groupby('Title')['user_score'].mean().sort_values(ascending=False).head()

Title
Rollerdrome                   8.017273
Dead Island: Ryder White      7.941000
PixelJunk Shooter Ultimate    7.732000
Mary Skelter Finale           7.730000
Triangle Strategy             7.701000
Name: user_score, dtype: float64

In [13]:
data.groupby('Title')['user_score'].count().sort_values(ascending=False).head()

Title
Mario Tennis: Ultra Smash              20
Shin Megami Tensei: Strange Journey    20
Pro Evolution Soccer 2018              20
The Legend of Dragoon                  20
Bleach: The Blade of Fate              20
Name: user_score, dtype: int64

In [15]:
data.groupby('Title').count().info

<bound method DataFrame.info of                                 Release Date  Developer  Publisher  Genres  \
Title
#DRIVE                                    11         11         11      11
#IDARB                                    16         16         16      16
'Splosion Man                             17         17         17      17
.detuned                                  11         11         11      11
.hack//G.U. Last Recode                   12         12         12      12
...                                      ...        ...        ...     ...
moon: Remix RPG Adventure                 16         16         16      16
nail'd                                    18         18         18      18
oOo: Ascension                            10         10         10      10
theHunter: Call of the Wild               19         19         19      19
void tRrLM(); //Void Terrarium            15         15         15      15

                                Product Rating  User Score  \
Title
#DRIVE                                      11          11
#IDARB                                      16          16
'Splosion Man                               17          17
.detuned                                    11          11
.hack//G.U. Last Recode                     12          12
...                                        ...         ...
moon: Remix RPG Adventure                   16          16
nail'd                                      18          18
oOo: Ascension                              10          10
theHunter: Call of the Wild                 19          19
void tRrLM(); //Void Terrarium              15          15

                                User Ratings Count  Platforms Info  \
Title
#DRIVE                                          11              11
#IDARB                                          16              16
'Splosion Man                                   17              17
.detuned                                        11              11
.hack//G.U. Last Recode                         12              12
...                                            ...             ...
moon: Remix RPG Adventure                       16              16
nail'd                                          18              18
oOo: Ascension                                  10              10
theHunter: Call of the Wild                     19              19
void tRrLM(); //Void Terrarium                  15              15

                                Platforms Info Cleaned  Platform Metascores  \
Title
#DRIVE                                              11                   11
#IDARB                                              16                   16
'Splosion Man                                       17                   17
.detuned                                            11                   11
.hack//G.U. Last Recode                             12                   12
...                                                ...                  ...
moon: Remix RPG Adventure                           16                   16
nail'd                                              18                   18
oOo: Ascension                                      10                   10
theHunter: Call of the Wild                         19                   19
void tRrLM(); //Void Terrarium                      15                   15

                                Platform Metascore Counts  user_id  user_score
Title
#DRIVE                                                 11       11          11
#IDARB                                                 16       16          16
'Splosion Man                                          17       17          17
.detuned                                               11       11          11
.hack//G.U. Last Recode                                12       12          12
...                                                   ...      ...         ...
moon: Remix RPG Adventure                              16       16          16
nail'd                                                 18       18          18
oOo: Ascension                                         10       10          10
theHunter: Call of the Wild                            19       19          19
void tRrLM(); //Void Terrarium                         15       15          15

[11252 rows x 13 columns]>

In [17]:
userscores = pd.DataFrame(data.groupby('Title')['user_score'].mean())  

userscores['total num of user score'] = pd.DataFrame(data.groupby('Title')['user_score'].count()) 

userscores

                                user_score  total num of user score
Title
#DRIVE                            4.780909                       11
#IDARB                            6.345000                       16
'Splosion Man                     4.370588                       17
.detuned                          5.422727                       11
.hack//G.U. Last Recode           5.703333                       12
...                                    ...                      ...
moon: Remix RPG Adventure         6.103750                       16
nail'd                            5.006111                       18
oOo: Ascension                    5.350000                       10
theHunter: Call of the Wild       5.320000                       19
void tRrLM(); //Void Terrarium    6.207333                       15

[11252 rows x 2 columns]

In [19]:
score_matrix = data.pivot_table(index='user_id', columns='Title', values='user_score', fill_value=0)

score_matrix.head()

userscores.sort_values('total num of user score', ascending = False).head(10)

                                     user_score  total num of user score
Title
Mario Tennis: Ultra Smash                4.9705                       20
Shin Megami Tensei: Strange Journey      4.2170                       20
Pro Evolution Soccer 2018                4.8415                       20
The Legend of Dragoon                    5.7855                       20
Bleach: The Blade of Fate                5.2525                       20
Fight Night Round 4                      5.9420                       20
Nebuchadnezzar                           5.4830                       20
Fighters Uncaged                         5.3780                       20
Naval War: Arctic Circle                 4.7255                       20
Naughty Bear: Panic in Paradise          5.1525                       20

In [21]:
game_user_score = score_matrix['Pro Evolution Soccer 2018'] 

game_user_score

user_id
user_1      5.13
user_10     3.20
user_100    0.00
user_11     0.00
user_12     0.00
            ...
user_95     0.00
user_96     0.00
user_97     0.00
user_98     5.09
user_99     3.10
Name: Pro Evolution Soccer 2018, Length: 100, dtype: float64

In [23]:
similar_to_game = score_matrix.corrwith(game_user_score)  
  
corr_drive = pd.DataFrame(similar_to_game, columns =['Correlation']) 
corr_drive.dropna(inplace = True) 
  
corr_drive.head()

                         Correlation
Title
#DRIVE                      0.176895
#IDARB                     -0.025724
'Splosion Man              -0.039203
.detuned                   -0.026495
.hack//G.U. Last Recode    -0.029023

In [25]:
print("corr_drive Sample Data:")
print(corr_drive.head())

print("\nuserscores Columns:", userscores.columns.tolist())
print("userscores Sample Data:")
print(userscores.head())

corr_drive Sample Data:
                         Correlation
Title
#DRIVE                      0.176895
#IDARB                     -0.025724
'Splosion Man              -0.039203
.detuned                   -0.026495
.hack//G.U. Last Recode    -0.029023

userscores Columns: ['user_score', 'total num of user score']
userscores Sample Data:
                         user_score  total num of user score
Title
#DRIVE                     4.780909                       11
#IDARB                     6.345000                       16
'Splosion Man              4.370588                       17
.detuned                   5.422727                       11
.hack//G.U. Last Recode    5.703333                       12

In [27]:
corr_drive = corr_drive.drop(columns=['total num of user score'], errors='ignore')

corr_drive_sorted = corr_drive.sort_values('Correlation', ascending=False).head(10)

merged_corr_drive = corr_drive_sorted.join(userscores['total num of user score'], how='left')

print("Top 10 Correlations:")
print(merged_corr_drive)

missing_scores = merged_corr_drive['total num of user score'].isnull().sum()
print(f"\nNumber of missing 'total num of user score': {missing_scores}")


merged_corr_drive.dropna(subset=['total num of user score'], inplace=True)

high_score_corr = merged_corr_drive[merged_corr_drive['total num of user score'] > 10].sort_values('Correlation', ascending=False).head()

print("\nCorrelations with 'total num of user score' > 10:")
print(high_score_corr)

Top 10 Correlations:
                                               Correlation  \
Title
Pro Evolution Soccer 2018                         1.000000
Anno 2070                                         0.559420
Watchmen: The End Is Nigh Complete Experience     0.465746
Star Conflict                                     0.447682
Aliens: Fireteam Elite                            0.433820
ONRUSH                                            0.422457
Hatoful Boyfriend: Holiday Star                   0.413475
Train Sim World                                   0.406345
Tempest 4000                                      0.399536
Call of Duty: Black Ops - First Strike            0.389230

                                               total num of user score
Title
Pro Evolution Soccer 2018                                           20
Anno 2070                                                           11
Watchmen: The End Is Nigh Complete Experience                       20
Star Conflict                                                       17
Aliens: Fireteam Elite                                              19
ONRUSH                                                              12
Hatoful Boyfriend: Holiday Star                                     12
Train Sim World                                                     17
Tempest 4000                                                        15
Call of Duty: Black Ops - First Strike                              17

Number of missing 'total num of user score': 0

Correlations with 'total num of user score' > 10:
                                               Correlation  \
Title
Pro Evolution Soccer 2018                         1.000000
Anno 2070                                         0.559420
Watchmen: The End Is Nigh Complete Experience     0.465746
Star Conflict                                     0.447682
Aliens: Fireteam Elite                            0.433820

                                               total num of user score
Title
Pro Evolution Soccer 2018                                           20
Anno 2070                                                           11
Watchmen: The End Is Nigh Complete Experience                       20
Star Conflict                                                       17
Aliens: Fireteam Elite                                              19